name: Run mypy / pylint

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  
  linting:
    
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2.4.2

      - name: Install Python 3
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.6.8'

      - name: Upgrade Pip :: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.13

      - name: Install Dependancies
        run: poetry install

      - name: Run mypy
        run: poetry run mypy .

      - name: Run pylint
        run: poetry run pylint ./kolsol

